/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-02-21 14:09:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/style.css", Long.valueOf(1739798112878L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html lang=\"ru\">\n");
      out.write("    <head>\n");
      out.write("        <style>\n");
      out.write("            ");
      out.write("body {\n");
      out.write("    font-family: arial;\n");
      out.write("    colour: #666666;\n");
      out.write("    padding: 10px;\n");
      out.write("    width: 90%;\n");
      out.write("    margin: 0 auto;}\n");
      out.write("\n");
      out.write("h1 {\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 10px;}\n");
      out.write("\n");
      out.write("h3 {\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 10px;}\n");
      out.write("\n");
      out.write("p {\n");
      out.write("    padding: 10px;}\n");
      out.write("\n");
      out.write("#header {\n");
      out.write("    position: fixed;\n");
      out.write("    top: 10px;\n");
      out.write("    width: 90%;\n");
      out.write("    text-align: center;\n");
      out.write("    border-style: solid;\n");
      out.write("    border-width: 2px;\n");
      out.write("    background-color: #aeaca8;\n");
      out.write("    border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#footer {\n");
      out.write("    text-align: right;\n");
      out.write("    border-width: 2px;\n");
      out.write("    background-color: #aeaca8;\n");
      out.write("    border-style: solid;\n");
      out.write("    padding: 10px;\n");
      out.write("    border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("        <title>java practice: main</title>\n");
      out.write("\n");
      out.write("        <meta name=\"description\" content=\"Ежедневная практика в java - лучший способ освоить данный язык программирования\"\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <div id=\"top\">\n");
      out.write("            <br/>\n");
      out.write("            <br/>\n");
      out.write("            <br/>\n");
      out.write("            <h1>Home page</h1>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <br/>\n");
      out.write("            / <a href=\"index.jsp\"><b>главная</b></a> /\n");
      out.write("            <a href=\"jsps/projects/index.jsp\"><b>проекты</b></a> /\n");
      out.write("            <a href=\"jsps/articles/index.jsp\"><b>конспекты</b></a> /\n");
      out.write("            <br/>\n");
      out.write("            <br/>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <h3>Классический текст Lorem Ipsum, используемый с XVI века</h3>\n");
      out.write("\n");
      out.write("        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore\n");
      out.write("        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("        aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum\n");
      out.write("        dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui\n");
      out.write("        officia deserunt mollit anim id est laborum.</p>\n");
      out.write("\n");
      out.write("        <h3>Абзац 1.10.32 \"de Finibus Bonorum et Malorum\", написанный Цицероном в 45 году н.э.</h3>\n");
      out.write("\n");
      out.write("        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("        totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta\n");
      out.write("        sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia\n");
      out.write("        consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui\n");
      out.write("        dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi\n");
      out.write("        tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam,\n");
      out.write("        quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi\n");
      out.write("        consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam\n");
      out.write("        nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"</p>\n");
      out.write("\n");
      out.write("<h3>Классический текст Lorem Ipsum, используемый с XVI века</h3>\n");
      out.write("\n");
      out.write("        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore\n");
      out.write("        et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("        aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum\n");
      out.write("        dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui\n");
      out.write("        officia deserunt mollit anim id est laborum.</p>\n");
      out.write("\n");
      out.write("        <h3>Абзац 1.10.32 \"de Finibus Bonorum et Malorum\", написанный Цицероном в 45 году н.э.</h3>\n");
      out.write("\n");
      out.write("        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("        totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta\n");
      out.write("        sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia\n");
      out.write("        consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui\n");
      out.write("        dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi\n");
      out.write("        tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam,\n");
      out.write("        quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi\n");
      out.write("        consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam\n");
      out.write("        nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"</p>\n");
      out.write("\n");
      out.write(" <h3>Классический текст Lorem Ipsum, используемый с XVI века</h3>\n");
      out.write("\n");
      out.write("         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore\n");
      out.write("         et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("         aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum\n");
      out.write("         dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui\n");
      out.write("         officia deserunt mollit anim id est laborum.</p>\n");
      out.write("\n");
      out.write("         <h3>Абзац 1.10.32 \"de Finibus Bonorum et Malorum\", написанный Цицероном в 45 году н.э.</h3>\n");
      out.write("\n");
      out.write("         <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("         totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta\n");
      out.write("         sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia\n");
      out.write("         consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui\n");
      out.write("         dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi\n");
      out.write("         tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam,\n");
      out.write("         quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi\n");
      out.write("         consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam\n");
      out.write("         nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"</p>\n");
      out.write("\n");
      out.write("  <h3>Классический текст Lorem Ipsum, используемый с XVI века</h3>\n");
      out.write("\n");
      out.write("          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore\n");
      out.write("          et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("          aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum\n");
      out.write("          dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui\n");
      out.write("          officia deserunt mollit anim id est laborum.</p>\n");
      out.write("\n");
      out.write("          <h3>Абзац 1.10.32 \"de Finibus Bonorum et Malorum\", написанный Цицероном в 45 году н.э.</h3>\n");
      out.write("\n");
      out.write("          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("          totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta\n");
      out.write("          sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia\n");
      out.write("          consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui\n");
      out.write("          dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi\n");
      out.write("          tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam,\n");
      out.write("          quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi\n");
      out.write("          consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam\n");
      out.write("          nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"</p>\n");
      out.write("\n");
      out.write(" <h3>Классический текст Lorem Ipsum, используемый с XVI века</h3>\n");
      out.write("\n");
      out.write("         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore\n");
      out.write("         et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut\n");
      out.write("         aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum\n");
      out.write("         dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui\n");
      out.write("         officia deserunt mollit anim id est laborum.</p>\n");
      out.write("\n");
      out.write("         <h3>Абзац 1.10.32 \"de Finibus Bonorum et Malorum\", написанный Цицероном в 45 году н.э.</h3>\n");
      out.write("\n");
      out.write("         <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,\n");
      out.write("         totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta\n");
      out.write("         sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia\n");
      out.write("         consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui\n");
      out.write("         dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi\n");
      out.write("         tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam,\n");
      out.write("         quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi\n");
      out.write("         consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam\n");
      out.write("         nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\"</p>\n");
      out.write("\n");
      out.write("        <div id=\"footer\">\n");
      out.write("            / <a href=\"#top\"><b>наверх</b></a> /\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
